action_id(id(78),activate_icls).
action_id(id(49),activate_tacan).
action_id(id(71),aerobatics).
action_id(id(81),airbone_drop_operation).
action_id(id(63),alarm_state).
action_id(id(35),anti_ship).
action_id(id(2),attack_group).
action_id(id(4),attack_map_object).
action_id(id(3),attack_unit).
action_id(id(26),awacs).
action_id(id(5),bombing).
action_id(id(6),bombing_runway).
action_id(id(33),cap).
action_id(id(19),cargo_transportation).
action_id(id(73),carpet_bombing).
action_id(id(32),cas).
action_id(id(50),deactivate_beacon).
action_id(id(79),deactivate_icls).
action_id(id(18),disembarking).
action_id(id(62),disperse_on_attack).
action_id(id(64),ecm_using).
action_id(id(17),embarking).
action_id(id(15),embark_to_transport).
action_id(id(72),engage_air_weapons).
action_id(id(24),engage_group).
action_id(id(22),engage_targets).
action_id(id(23),engage_targets_in_zone).
action_id(id(25),engage_unit).
action_id(id(51),eplrs).
action_id(id(14),escort).
action_id(id(27),ewr).
action_id(id(28),fac).
action_id(id(10),fac_attack_group).
action_id(id(29),fac_engage_group).
action_id(id(31),fighter_sweep).
action_id(id(11),fire_at_point).
action_id(id(57),flare_using).
action_id(id(13),follow).
action_id(id(58),formation).
action_id(id(16),go_to_waypoint).
action_id(id(20),ground_escort).
action_id(id(12),hold).
action_id(id(47),immortal).
action_id(id(46),invisible).
action_id(id(8),land).
action_id(id(69),missile_attack).
action_id(id(36),no_action).
action_id(id(21),no_enroute_task).
action_id(id(53),no_option).
action_id(id(1),no_task).
action_id(id(7),orbit).
action_id(id(80),paratroopers_drop).
action_id(id(65),prohibit_aa).
action_id(id(67),prohibit_ab).
action_id(id(68),prohibit_ag).
action_id(id(66),prohibit_jett).
action_id(id(70),prohibit_wp_pass_report).
action_id(id(56),radar_using).
action_id(id(75),radio_usage_contact).
action_id(id(76),radio_usage_engage).
action_id(id(77),radio_usage_kill).
action_id(id(55),reaction_on_threat).
action_id(id(9),refueling).
action_id(id(54),roe).
action_id(id(59),rtb_on_bingo).
action_id(id(60),rtb_on_out_of_ammo).
action_id(id(37),script).
action_id(id(38),script_file).
action_id(id(34),sead).
action_id(id(39),set_callsign).
action_id(id(40),set_frequency).
action_id(id(41),set_frequencyforunit).
action_id(id(61),silence).
action_id(id(52),smoke_on_off).
action_id(id(48),start).
action_id(id(43),stop_transmission).
action_id(id(45),switch_item).
action_id(id(44),switch_waypoint).
action_id(id(30),tanker).
action_id(id(42),transmit_message).
action_id(id(74),ww2_big_formation).
