:- module(dcs_world_callnames, [callname_property/2]).

/** <module> Callsign names
 *
 * Call names (short for callsign  names)   are  the names of aircraft,
 * heavy aircraft, vehicles, reference points,   AWACS, helipads, grass
 * airfields and aircraft carriers. Enfield,  Springfield, Uzi and Colt
 * are  the  first  four  aircraft  call   names,  for  example.  Named
 * presumably for guns. Axeman, Darknight,   Warrior and Pointer belong
 * to ground vehicles, as  another  example.   London  and  Dallas  for
 * helipads, and so on.
 *
 * Call names belong to a category and a   country.  Each has a name, a
 * world identifier plus an optional  sound   file.  They are important
 * because the mission payloads include   mandatory  callsign names and
 * numbers. In raw form, the call-name  payloads deconstruct by country
 * then category. Raw country uses  the   world  integer identifier for
 * country representation. The cooked version  of the call-name payload
 * maps the raw country identifier with its   atomic name, also the raw
 * category name as well as the cooked category atom.
 *
 * Important to note that  call  names   are  not  unique outside their
 * category. There are no  less  than   three  Enfield  call  names for
 * example; one for A-10A, another for A-10C   and  a final one for Air
 * category. For this reason, Callname is a   compound term of the form
 * Category(Name)   and   hence   disambiguates     for    Enfield   as
 * a_10a(enfield), a_10c(enfield) and air(enfield). They carry the same
 * world identifier in the current versions of DCS; see below.
 *
 *     ?- callname_property(Callname, world_id(ID)), Callname =.. [_, enfield].
 *     Callname = a_10a(enfield), ID = 1 ;
 *     Callname = a_10c(enfield), ID = 1 ;
 *     Callname = air(enfield), ID = 1 ;
 *     false.
 *
 * @author R3DL1N3 <r0y@digitalcombatsimulator.world>
 */

:- multifile dcs:property_of_callname/2.

%!  callname_property(?Callname:compound, ?Property) is nondet.
%
%   Property of Callname.

callname_property(Callname, Property) :-
    callname(Callname, Property).
callname_property(Callname, Property) :-
    dcs:property_of_callname(Property, Callname).

callname(aircraft_carriers(salamander),country(rus)).
callname(aircraft_carriers(salamander),category(aircraft_carriers)).
callname(aircraft_carriers(salamander),name("Salamander")).
callname(aircraft_carriers(salamander),world_id(1)).
callname(grass_airfield(a01),country(rus)).
callname(grass_airfield(a01),category(grass_airfield)).
callname(grass_airfield(a01),name("A01")).
callname(grass_airfield(a01),world_id(1)).
callname(grass_airfield(a01),sound_file("A01")).
callname(grass_airfield(b01),country(rus)).
callname(grass_airfield(b01),category(grass_airfield)).
callname(grass_airfield(b01),name("B01")).
callname(grass_airfield(b01),world_id(2)).
callname(grass_airfield(b01),sound_file("B01")).
callname(helipad(otkrytka),country(rus)).
callname(helipad(otkrytka),category(helipad)).
callname(helipad(otkrytka),name("Otkrytka")).
callname(helipad(otkrytka),world_id(1)).
callname(helipad(otkrytka),sound_file("Otkrytka")).
callname(helipad(vetka),country(rus)).
callname(helipad(vetka),category(helipad)).
callname(helipad(vetka),name("Vetka")).
callname(helipad(vetka),world_id(2)).
callname(helipad(vetka),sound_file("Vetka")).
callname(helipad(yunga),country(rus)).
callname(helipad(yunga),category(helipad)).
callname(helipad(yunga),name("Yunga")).
callname(helipad(yunga),world_id(3)).
callname(helipad(yunga),sound_file("Yunga")).
callname(helipad(shpora),country(rus)).
callname(helipad(shpora),category(helipad)).
callname(helipad(shpora),name("Shpora")).
callname(helipad(shpora),world_id(4)).
callname(helipad(shpora),sound_file("Shpora")).
callname(helipad(kalitka),country(rus)).
callname(helipad(kalitka),category(helipad)).
callname(helipad(kalitka),name("Kalitka")).
callname(helipad(kalitka),world_id(5)).
callname(helipad(kalitka),sound_file("Kalitka")).
callname(helipad(torba),country(rus)).
callname(helipad(torba),category(helipad)).
callname(helipad(torba),name("Torba")).
callname(helipad(torba),world_id(6)).
callname(helipad(torba),sound_file("Torba")).
callname(helipad(kaemka),country(rus)).
callname(helipad(kaemka),category(helipad)).
callname(helipad(kaemka),name("Kaemka")).
callname(helipad(kaemka),world_id(7)).
callname(helipad(kaemka),sound_file("Kaemka")).
callname(helipad(podkova),country(rus)).
callname(helipad(podkova),category(helipad)).
callname(helipad(podkova),name("Podkova")).
callname(helipad(podkova),world_id(8)).
callname(helipad(podkova),sound_file("Podkova")).
callname(helipad(skala),country(rus)).
callname(helipad(skala),category(helipad)).
callname(helipad(skala),name("Skala")).
callname(helipad(skala),world_id(9)).
callname(helipad(skala),sound_file("Skala")).
callname(helipad(kapel),country(rus)).
callname(helipad(kapel),category(helipad)).
callname(helipad(kapel),name("Kapel")).
callname(helipad(kapel),world_id(10)).
callname(helipad(kapel),sound_file("Kapel")).
callname(a_10a(enfield),country(usa)).
callname(a_10a(enfield),category(a_10a)).
callname(a_10a(enfield),name("Enfield")).
callname(a_10a(enfield),world_id(1)).
callname(a_10a(enfield),sound_file("Enfield")).
callname(a_10a(springfield),country(usa)).
callname(a_10a(springfield),category(a_10a)).
callname(a_10a(springfield),name("Springfield")).
callname(a_10a(springfield),world_id(2)).
callname(a_10a(springfield),sound_file("Springfield")).
callname(a_10a(uzi),country(usa)).
callname(a_10a(uzi),category(a_10a)).
callname(a_10a(uzi),name("Uzi")).
callname(a_10a(uzi),world_id(3)).
callname(a_10a(uzi),sound_file("Uzi")).
callname(a_10a(colt),country(usa)).
callname(a_10a(colt),category(a_10a)).
callname(a_10a(colt),name("Colt")).
callname(a_10a(colt),world_id(4)).
callname(a_10a(colt),sound_file("Colt")).
callname(a_10a(dodge),country(usa)).
callname(a_10a(dodge),category(a_10a)).
callname(a_10a(dodge),name("Dodge")).
callname(a_10a(dodge),world_id(5)).
callname(a_10a(dodge),sound_file("Dodge")).
callname(a_10a(ford),country(usa)).
callname(a_10a(ford),category(a_10a)).
callname(a_10a(ford),name("Ford")).
callname(a_10a(ford),world_id(6)).
callname(a_10a(ford),sound_file("Ford")).
callname(a_10a(chevy),country(usa)).
callname(a_10a(chevy),category(a_10a)).
callname(a_10a(chevy),name("Chevy")).
callname(a_10a(chevy),world_id(7)).
callname(a_10a(chevy),sound_file("Chevy")).
callname(a_10a(pontiac),country(usa)).
callname(a_10a(pontiac),category(a_10a)).
callname(a_10a(pontiac),name("Pontiac")).
callname(a_10a(pontiac),world_id(8)).
callname(a_10a(pontiac),sound_file("Pontiac")).
callname(a_10a(hawg),country(usa)).
callname(a_10a(hawg),category(a_10a)).
callname(a_10a(hawg),name("Hawg")).
callname(a_10a(hawg),world_id(9)).
callname(a_10a(hawg),sound_file("Hawg")).
callname(a_10a(boar),country(usa)).
callname(a_10a(boar),category(a_10a)).
callname(a_10a(boar),name("Boar")).
callname(a_10a(boar),world_id(10)).
callname(a_10a(boar),sound_file("Boar")).
callname(a_10a(pig),country(usa)).
callname(a_10a(pig),category(a_10a)).
callname(a_10a(pig),name("Pig")).
callname(a_10a(pig),world_id(11)).
callname(a_10a(pig),sound_file("Pig")).
callname(a_10a(tusk),country(usa)).
callname(a_10a(tusk),category(a_10a)).
callname(a_10a(tusk),name("Tusk")).
callname(a_10a(tusk),world_id(12)).
callname(a_10a(tusk),sound_file("Tusk")).
callname(a_10c(enfield),country(usa)).
callname(a_10c(enfield),category(a_10c)).
callname(a_10c(enfield),name("Enfield")).
callname(a_10c(enfield),world_id(1)).
callname(a_10c(enfield),sound_file("Enfield")).
callname(a_10c(springfield),country(usa)).
callname(a_10c(springfield),category(a_10c)).
callname(a_10c(springfield),name("Springfield")).
callname(a_10c(springfield),world_id(2)).
callname(a_10c(springfield),sound_file("Springfield")).
callname(a_10c(uzi),country(usa)).
callname(a_10c(uzi),category(a_10c)).
callname(a_10c(uzi),name("Uzi")).
callname(a_10c(uzi),world_id(3)).
callname(a_10c(uzi),sound_file("Uzi")).
callname(a_10c(colt),country(usa)).
callname(a_10c(colt),category(a_10c)).
callname(a_10c(colt),name("Colt")).
callname(a_10c(colt),world_id(4)).
callname(a_10c(colt),sound_file("Colt")).
callname(a_10c(dodge),country(usa)).
callname(a_10c(dodge),category(a_10c)).
callname(a_10c(dodge),name("Dodge")).
callname(a_10c(dodge),world_id(5)).
callname(a_10c(dodge),sound_file("Dodge")).
callname(a_10c(ford),country(usa)).
callname(a_10c(ford),category(a_10c)).
callname(a_10c(ford),name("Ford")).
callname(a_10c(ford),world_id(6)).
callname(a_10c(ford),sound_file("Ford")).
callname(a_10c(chevy),country(usa)).
callname(a_10c(chevy),category(a_10c)).
callname(a_10c(chevy),name("Chevy")).
callname(a_10c(chevy),world_id(7)).
callname(a_10c(chevy),sound_file("Chevy")).
callname(a_10c(pontiac),country(usa)).
callname(a_10c(pontiac),category(a_10c)).
callname(a_10c(pontiac),name("Pontiac")).
callname(a_10c(pontiac),world_id(8)).
callname(a_10c(pontiac),sound_file("Pontiac")).
callname(a_10c(hawg),country(usa)).
callname(a_10c(hawg),category(a_10c)).
callname(a_10c(hawg),name("Hawg")).
callname(a_10c(hawg),world_id(9)).
callname(a_10c(hawg),sound_file("Hawg")).
callname(a_10c(boar),country(usa)).
callname(a_10c(boar),category(a_10c)).
callname(a_10c(boar),name("Boar")).
callname(a_10c(boar),world_id(10)).
callname(a_10c(boar),sound_file("Boar")).
callname(a_10c(pig),country(usa)).
callname(a_10c(pig),category(a_10c)).
callname(a_10c(pig),name("Pig")).
callname(a_10c(pig),world_id(11)).
callname(a_10c(pig),sound_file("Pig")).
callname(a_10c(tusk),country(usa)).
callname(a_10c(tusk),category(a_10c)).
callname(a_10c(tusk),name("Tusk")).
callname(a_10c(tusk),world_id(12)).
callname(a_10c(tusk),sound_file("Tusk")).
callname(awacs(overlord),country(usa)).
callname(awacs(overlord),category(awacs)).
callname(awacs(overlord),name("Overlord")).
callname(awacs(overlord),world_id(1)).
callname(awacs(magic),country(usa)).
callname(awacs(magic),category(awacs)).
callname(awacs(magic),name("Magic")).
callname(awacs(magic),world_id(2)).
callname(awacs(wizard),country(usa)).
callname(awacs(wizard),category(awacs)).
callname(awacs(wizard),name("Wizard")).
callname(awacs(wizard),world_id(3)).
callname(awacs(focus),country(usa)).
callname(awacs(focus),category(awacs)).
callname(awacs(focus),name("Focus")).
callname(awacs(focus),world_id(4)).
callname(awacs(darkstar),country(usa)).
callname(awacs(darkstar),category(awacs)).
callname(awacs(darkstar),name("Darkstar")).
callname(awacs(darkstar),world_id(5)).
callname(air(enfield),country(usa)).
callname(air(enfield),category(air)).
callname(air(enfield),name("Enfield")).
callname(air(enfield),world_id(1)).
callname(air(enfield),sound_file("Enfield")).
callname(air(springfield),country(usa)).
callname(air(springfield),category(air)).
callname(air(springfield),name("Springfield")).
callname(air(springfield),world_id(2)).
callname(air(springfield),sound_file("Springfield")).
callname(air(uzi),country(usa)).
callname(air(uzi),category(air)).
callname(air(uzi),name("Uzi")).
callname(air(uzi),world_id(3)).
callname(air(uzi),sound_file("Uzi")).
callname(air(colt),country(usa)).
callname(air(colt),category(air)).
callname(air(colt),name("Colt")).
callname(air(colt),world_id(4)).
callname(air(colt),sound_file("Colt")).
callname(air(dodge),country(usa)).
callname(air(dodge),category(air)).
callname(air(dodge),name("Dodge")).
callname(air(dodge),world_id(5)).
callname(air(dodge),sound_file("Dodge")).
callname(air(ford),country(usa)).
callname(air(ford),category(air)).
callname(air(ford),name("Ford")).
callname(air(ford),world_id(6)).
callname(air(ford),sound_file("Ford")).
callname(air(chevy),country(usa)).
callname(air(chevy),category(air)).
callname(air(chevy),name("Chevy")).
callname(air(chevy),world_id(7)).
callname(air(chevy),sound_file("Chevy")).
callname(air(pontiac),country(usa)).
callname(air(pontiac),category(air)).
callname(air(pontiac),name("Pontiac")).
callname(air(pontiac),world_id(8)).
callname(air(pontiac),sound_file("Pontiac")).
callname(aircraft_carriers(stennis),country(usa)).
callname(aircraft_carriers(stennis),category(aircraft_carriers)).
callname(aircraft_carriers(stennis),name("Stennis")).
callname(aircraft_carriers(stennis),world_id(1)).
callname(aircraft_carriers(winson),country(usa)).
callname(aircraft_carriers(winson),category(aircraft_carriers)).
callname(aircraft_carriers(winson),name("Winson")).
callname(aircraft_carriers(winson),world_id(2)).
callname(aux(raider),country(usa)).
callname(aux(raider),category(aux)).
callname(aux(raider),name("Raider")).
callname(aux(raider),world_id(1)).
callname(aux(raider),sound_file("Raider")).
callname(grass_airfield(new_york),country(usa)).
callname(grass_airfield(new_york),category(grass_airfield)).
callname(grass_airfield(new_york),name("New York")).
callname(grass_airfield(new_york),world_id(1)).
callname(grass_airfield(new_york),sound_file("New York")).
callname(ground_units(axeman),country(usa)).
callname(ground_units(axeman),category(ground_units)).
callname(ground_units(axeman),name("Axeman")).
callname(ground_units(axeman),world_id(1)).
callname(ground_units(darknight),country(usa)).
callname(ground_units(darknight),category(ground_units)).
callname(ground_units(darknight),name("Darknight")).
callname(ground_units(darknight),world_id(2)).
callname(ground_units(warrior),country(usa)).
callname(ground_units(warrior),category(ground_units)).
callname(ground_units(warrior),name("Warrior")).
callname(ground_units(warrior),world_id(3)).
callname(ground_units(pointer),country(usa)).
callname(ground_units(pointer),category(ground_units)).
callname(ground_units(pointer),name("Pointer")).
callname(ground_units(pointer),world_id(4)).
callname(ground_units(eyeball),country(usa)).
callname(ground_units(eyeball),category(ground_units)).
callname(ground_units(eyeball),name("Eyeball")).
callname(ground_units(eyeball),world_id(5)).
callname(ground_units(moonbeam),country(usa)).
callname(ground_units(moonbeam),category(ground_units)).
callname(ground_units(moonbeam),name("Moonbeam")).
callname(ground_units(moonbeam),world_id(6)).
callname(ground_units(whiplash),country(usa)).
callname(ground_units(whiplash),category(ground_units)).
callname(ground_units(whiplash),name("Whiplash")).
callname(ground_units(whiplash),world_id(7)).
callname(ground_units(finger),country(usa)).
callname(ground_units(finger),category(ground_units)).
callname(ground_units(finger),name("Finger")).
callname(ground_units(finger),world_id(8)).
callname(ground_units(pinpoint),country(usa)).
callname(ground_units(pinpoint),category(ground_units)).
callname(ground_units(pinpoint),name("Pinpoint")).
callname(ground_units(pinpoint),world_id(9)).
callname(ground_units(ferret),country(usa)).
callname(ground_units(ferret),category(ground_units)).
callname(ground_units(ferret),name("Ferret")).
callname(ground_units(ferret),world_id(10)).
callname(ground_units(shaba),country(usa)).
callname(ground_units(shaba),category(ground_units)).
callname(ground_units(shaba),name("Shaba")).
callname(ground_units(shaba),world_id(11)).
callname(ground_units(playboy),country(usa)).
callname(ground_units(playboy),category(ground_units)).
callname(ground_units(playboy),name("Playboy")).
callname(ground_units(playboy),world_id(12)).
callname(ground_units(hammer),country(usa)).
callname(ground_units(hammer),category(ground_units)).
callname(ground_units(hammer),name("Hammer")).
callname(ground_units(hammer),world_id(13)).
callname(ground_units(jaguar),country(usa)).
callname(ground_units(jaguar),category(ground_units)).
callname(ground_units(jaguar),name("Jaguar")).
callname(ground_units(jaguar),world_id(14)).
callname(ground_units(deathstar),country(usa)).
callname(ground_units(deathstar),category(ground_units)).
callname(ground_units(deathstar),name("Deathstar")).
callname(ground_units(deathstar),world_id(15)).
callname(ground_units(anvil),country(usa)).
callname(ground_units(anvil),category(ground_units)).
callname(ground_units(anvil),name("Anvil")).
callname(ground_units(anvil),world_id(16)).
callname(ground_units(firefly),country(usa)).
callname(ground_units(firefly),category(ground_units)).
callname(ground_units(firefly),name("Firefly")).
callname(ground_units(firefly),world_id(17)).
callname(ground_units(mantis),country(usa)).
callname(ground_units(mantis),category(ground_units)).
callname(ground_units(mantis),name("Mantis")).
callname(ground_units(mantis),world_id(18)).
callname(ground_units(badger),country(usa)).
callname(ground_units(badger),category(ground_units)).
callname(ground_units(badger),name("Badger")).
callname(ground_units(badger),world_id(19)).
callname(helipad(london),country(usa)).
callname(helipad(london),category(helipad)).
callname(helipad(london),name("London")).
callname(helipad(london),world_id(1)).
callname(helipad(london),sound_file("London")).
callname(helipad(dallas),country(usa)).
callname(helipad(dallas),category(helipad)).
callname(helipad(dallas),name("Dallas")).
callname(helipad(dallas),world_id(2)).
callname(helipad(dallas),sound_file("Dallas")).
callname(helipad(paris),country(usa)).
callname(helipad(paris),category(helipad)).
callname(helipad(paris),name("Paris")).
callname(helipad(paris),world_id(3)).
callname(helipad(paris),sound_file("Paris")).
callname(helipad(moscow),country(usa)).
callname(helipad(moscow),category(helipad)).
callname(helipad(moscow),name("Moscow")).
callname(helipad(moscow),world_id(4)).
callname(helipad(moscow),sound_file("Moscow")).
callname(helipad(berlin),country(usa)).
callname(helipad(berlin),category(helipad)).
callname(helipad(berlin),name("Berlin")).
callname(helipad(berlin),world_id(5)).
callname(helipad(berlin),sound_file("Berlin")).
callname(helipad(rome),country(usa)).
callname(helipad(rome),category(helipad)).
callname(helipad(rome),name("Rome")).
callname(helipad(rome),world_id(6)).
callname(helipad(rome),sound_file("Rome")).
callname(helipad(madrid),country(usa)).
callname(helipad(madrid),category(helipad)).
callname(helipad(madrid),name("Madrid")).
callname(helipad(madrid),world_id(7)).
callname(helipad(madrid),sound_file("Madrid")).
callname(helipad(warsaw),country(usa)).
callname(helipad(warsaw),category(helipad)).
callname(helipad(warsaw),name("Warsaw")).
callname(helipad(warsaw),world_id(8)).
callname(helipad(warsaw),sound_file("Warsaw")).
callname(helipad(dublin),country(usa)).
callname(helipad(dublin),category(helipad)).
callname(helipad(dublin),name("Dublin")).
callname(helipad(dublin),world_id(9)).
callname(helipad(dublin),sound_file("Dublin")).
callname(helipad(perth),country(usa)).
callname(helipad(perth),category(helipad)).
callname(helipad(perth),name("Perth")).
callname(helipad(perth),world_id(10)).
callname(helipad(perth),sound_file("Perth")).
callname(ref_points(ford),country(usa)).
callname(ref_points(ford),category(ref_points)).
callname(ref_points(ford),name("FORD")).
callname(ref_points(ford),world_id(1)).
callname(ref_points(edsel),country(usa)).
callname(ref_points(edsel),category(ref_points)).
callname(ref_points(edsel),name("EDSEL")).
callname(ref_points(edsel),world_id(2)).
callname(ref_points(dodge),country(usa)).
callname(ref_points(dodge),category(ref_points)).
callname(ref_points(dodge),name("DODGE")).
callname(ref_points(dodge),world_id(3)).
callname(ref_points(mazda),country(usa)).
callname(ref_points(mazda),category(ref_points)).
callname(ref_points(mazda),name("MAZDA")).
callname(ref_points(mazda),world_id(4)).
callname(ref_points(banks),country(usa)).
callname(ref_points(banks),category(ref_points)).
callname(ref_points(banks),name("BANKS")).
callname(ref_points(banks),world_id(5)).
callname(ref_points(chevy),country(usa)).
callname(ref_points(chevy),category(ref_points)).
callname(ref_points(chevy),name("CHEVY")).
callname(ref_points(chevy),world_id(6)).
callname(ref_points(towel),country(usa)).
callname(ref_points(towel),category(ref_points)).
callname(ref_points(towel),name("TOWEL")).
callname(ref_points(towel),world_id(7)).
callname(ref_points(adder),country(usa)).
callname(ref_points(adder),category(ref_points)).
callname(ref_points(adder),name("ADDER")).
callname(ref_points(adder),world_id(8)).
callname(strategic_bombers(raider),country(usa)).
callname(strategic_bombers(raider),category(strategic_bombers)).
callname(strategic_bombers(raider),name("Raider")).
callname(strategic_bombers(raider),world_id(1)).
callname(strategic_bombers(raider),sound_file("Raider")).
callname(tankers(texaco),country(usa)).
callname(tankers(texaco),category(tankers)).
callname(tankers(texaco),name("Texaco")).
callname(tankers(texaco),world_id(1)).
callname(tankers(arco),country(usa)).
callname(tankers(arco),category(tankers)).
callname(tankers(arco),name("Arco")).
callname(tankers(arco),world_id(2)).
callname(tankers(shell),country(usa)).
callname(tankers(shell),category(tankers)).
callname(tankers(shell),name("Shell")).
callname(tankers(shell),world_id(3)).
callname(transports(raider),country(usa)).
callname(transports(raider),category(transports)).
callname(transports(raider),name("Raider")).
callname(transports(raider),world_id(1)).
callname(transports(raider),sound_file("Raider")).
callname(awacs(solex),country(uk)).
callname(awacs(solex),category(awacs)).
callname(awacs(solex),name("Solex")).
callname(awacs(solex),world_id(1)).
callname(awacs(image),country(uk)).
callname(awacs(image),category(awacs)).
callname(awacs(image),name("Image")).
callname(awacs(image),world_id(2)).
callname(awacs(cyrano),country(fra)).
callname(awacs(cyrano),category(awacs)).
callname(awacs(cyrano),name("Cyrano")).
callname(awacs(cyrano),world_id(1)).
callname(awacs(roxanne),country(fra)).
callname(awacs(roxanne),category(awacs)).
callname(awacs(roxanne),name("Roxanne")).
callname(awacs(roxanne),world_id(2)).
