of_option(allow_in_simulation(true),capto_glove).
of_option(icon("./CoreMods/services/CaptoGlove/Options/icon.png"),capto_glove).
of_option(id("CaptoGlove"),capto_glove).
of_option(module_location("./CoreMods/services/CaptoGlove"),capto_glove).
of_option(name("Capto Glove"),capto_glove).
of_option(options_folder("./CoreMods/services/CaptoGlove/Options"),capto_glove).
of_option(id("CA"),ca).
of_option(module_location("./Mods/tech/CombinedArms"),ca).
of_option(name("CA"),ca).
of_option(options_folder("./Mods/tech/CombinedArms/Options"),ca).
of_option(skin_folder("./Mods/tech/CombinedArms/Skins/1"),ca).
of_option(id("A-10C"),a_10c).
of_option(module_location("./Mods/aircraft/A-10C"),a_10c).
of_option(name("A-10C"),a_10c).
of_option(options_folder("./Mods/aircraft/A-10C/Options"),a_10c).
of_option(skin_folder("./Mods/aircraft/A-10C/Skins/1"),a_10c).
of_option(id("AV8BNA"),av8bna).
of_option(module_location("./Mods/aircraft/AV8BNA"),av8bna).
of_option(name("AV-8B N/A"),av8bna).
of_option(options_folder("./Mods/aircraft/AV8BNA/Options"),av8bna).
of_option(skin_folder("./Mods/aircraft/AV8BNA/Skins/1"),av8bna).
of_option(id("Bf-109K-4"),bf_109k_4).
of_option(module_location("./Mods/aircraft/Bf-109K-4"),bf_109k_4).
of_option(name("Bf 109 K-4"),bf_109k_4).
of_option(options_folder("./Mods/aircraft/Bf-109K-4/Options"),bf_109k_4).
of_option(skin_folder("./Mods/aircraft/Bf-109K-4/Skins/1"),bf_109k_4).
of_option(id("F-86F"),f_86f).
of_option(module_location("./Mods/aircraft/F-86"),f_86f).
of_option(name("F-86F"),f_86f).
of_option(options_folder("./Mods/aircraft/F-86/Options"),f_86f).
of_option(skin_folder("./Mods/aircraft/F-86/Skins/1"),f_86f).
of_option(id("F-14B"),f_14b).
of_option(module_location("./Mods/aircraft/F14"),f_14b).
of_option(name("F-14B"),f_14b).
of_option(options_folder("./Mods/aircraft/F14/Options"),f_14b).
of_option(skin_folder("./Mods/aircraft/F14/Skins"),f_14b).
of_option(aircraft_settings_file("AircraftSettings.lua"),f_a_18c).
of_option(id("F/A-18C"),f_a_18c).
of_option(module_location("./Mods/aircraft/FA-18C"),f_a_18c).
of_option(name("F/A-18C"),f_a_18c).
of_option(options_folder("./Mods/aircraft/FA-18C/Options"),f_a_18c).
of_option(skin_folder("./Mods/aircraft/FA-18C/Skins/1"),f_a_18c).
of_option(id("FW-190A8"),fw_190a8).
of_option(module_location("./Mods/aircraft/FW-190A8"),fw_190a8).
of_option(name("Fw 190 A-8"),fw_190a8).
of_option(options_folder("./Mods/aircraft/FW-190A8/Options"),fw_190a8).
of_option(skin_folder("./Mods/aircraft/FW-190A8/Skins/1"),fw_190a8).
of_option(id("FW-190D9"),fw_190d9).
of_option(module_location("./Mods/aircraft/FW-190D9"),fw_190d9).
of_option(name("Fw 190 D-9"),fw_190d9).
of_option(options_folder("./Mods/aircraft/FW-190D9/Options"),fw_190d9).
of_option(skin_folder("./Mods/aircraft/FW-190D9/Skins/1"),fw_190d9).
of_option(id("Ka-50"),ka_50).
of_option(module_location("./Mods/aircraft/Ka-50"),ka_50).
of_option(name("Ka-50"),ka_50).
of_option(options_folder("./Mods/aircraft/Ka-50/Options"),ka_50).
of_option(skin_folder("./Mods/aircraft/Ka-50/Skins/1"),ka_50).
of_option(id("M-2000C"),m_2000c).
of_option(module_location("./Mods/aircraft/M-2000C"),m_2000c).
of_option(name("M-2000C"),m_2000c).
of_option(options_folder("./Mods/aircraft/M-2000C/Options"),m_2000c).
of_option(skin_folder("./Mods/aircraft/M-2000C/Skins/1"),m_2000c).
of_option(id("Mi-8MTV2"),mi_8mtv2).
of_option(module_location("./Mods/aircraft/Mi-8MTV2"),mi_8mtv2).
of_option(name("Mi-8MTV2"),mi_8mtv2).
of_option(options_folder("./Mods/aircraft/Mi-8MTV2/Options"),mi_8mtv2).
of_option(skin_folder("./Mods/aircraft/Mi-8MTV2/Skins/1"),mi_8mtv2).
of_option(id("P-51D"),p_51d).
of_option(module_location("./Mods/aircraft/P-51D"),p_51d).
of_option(name("P-51D"),p_51d).
of_option(options_folder("./Mods/aircraft/P-51D/Options"),p_51d).
of_option(skin_folder("./Mods/aircraft/P-51D/Skins/1"),p_51d).
of_option(id("SA342"),sa342).
of_option(module_location("./Mods/aircraft/SA342"),sa342).
of_option(name("SA342"),sa342).
of_option(options_folder("./Mods/aircraft/SA342/Options"),sa342).
of_option(skin_folder("./Mods/aircraft/SA342/Skins/1"),sa342).
of_option(id("SpitfireLFMkIX"),spitfire_lfmk_ix).
of_option(module_location("./Mods/aircraft/SpitfireLFMkIX"),spitfire_lfmk_ix).
of_option(name("Spitfire LF Mk. IX"),spitfire_lfmk_ix).
of_option(options_folder("./Mods/aircraft/SpitfireLFMkIX/Options"),spitfire_lfmk_ix).
of_option(skin_folder("./Mods/aircraft/SpitfireLFMkIX/Skins/1"),spitfire_lfmk_ix).
of_option(id("Su-25T"),su_25t).
of_option(module_location("./Mods/aircraft/Su-25T"),su_25t).
of_option(name("Su-25T"),su_25t).
of_option(options_folder("./Mods/aircraft/Su-25T/Options"),su_25t).
of_option(skin_folder("./Mods/aircraft/Su-25T/Theme"),su_25t).
of_option(id("Su-33"),su_33).
of_option(module_location("./Mods/aircraft/Su-33"),su_33).
of_option(name("Su-33"),su_33).
of_option(options_folder("./Mods/aircraft/Su-33/Options"),su_33).
of_option(skin_folder("./Mods/aircraft/Su-33/Skins/1"),su_33).
of_option(id("TF-51D"),tf_51d).
of_option(module_location("./Mods/aircraft/TF-51D"),tf_51d).
of_option(name("TF-51D"),tf_51d).
of_option(options_folder("./Mods/aircraft/TF-51D/Options"),tf_51d).
of_option(skin_folder("./Mods/aircraft/TF-51D/Skins/1"),tf_51d).
of_option(id("UH-1H"),uh_1h).
of_option(module_location("./Mods/aircraft/Uh-1H"),uh_1h).
of_option(name("UH-1H"),uh_1h).
of_option(options_folder("./Mods/aircraft/Uh-1H/Options"),uh_1h).
of_option(skin_folder("./Mods/aircraft/Uh-1H/Skins/1"),uh_1h).
